### PR TITLE
bugfix(debug): Fix memory corruption in DebugCrash()

### LINKED ISSUE #1365: Debug VC6 build crashes
The debug VC6 build is broken in main. It crashes after the intro when started without -quickstart.
Here is the crash:

Image

Here is the callstack:

Image

Note that TerrainDecalTextureName in the callstack is not a function. There is some stack corruption going on.

PR #1035 doesn't crash. The bug must have gotten introduced sometime since then.

### PR DESCRIPTION
**Pull request by xezon**
**Merge with Rebase**

* Fixes #1365
* Follow up for #1275

This change fixes the memory corruption in DebugCrash().

It has 2 commits. The first is the bug fix. The second is fixing a few more theoretical offenders in Debug.cpp.

The corruption was introduced by #1275 and only manifested as a runtime issue in VC6 Debug because of #858.

### CODE REVIEW

File: Generals/Code/GameEngine/Source/Common/System/Debug.cpp [hunk 1]
```diff
@@ -192,7 +192,7 @@ static const char *getCurrentTimeString(void)
 static const char *getCurrentTickString(void)
 {
 	static char TheTickString[32];
-	sprintf(TheTickString, "(T=%08lx)",::GetTickCount());
+	snprintf(TheTickString, ARRAY_SIZE(TheTickString), "(T=%08lx)",::GetTickCount());
```
Comment (Caball009) [inline Generals/Code/GameEngine/Source/Common/System/Debug.cpp]: Inconsistent spacing between function arguments.

**Review by Caball009 — APPROVED** [review]
Have not checked if this deals with all potential offenders, but it fixes the immediate crash.

**Comment by xezon** [comment]
In a follow up we can make the zero write in vsnprintf in stdio_adapter.h conditional.
